### ISSUE TITLE
error on (re)starting jellyfin

### ISSUE THREAD

**Issue by ronajon** [RTUnit/Jellyfin-Transcodes-cleanup#4]
when jellyfin is restarted, a transcode.cleanup.log file is created with following messages 
"FFMPEG started without transcoding directory as argument, so will not launch clean-up process because there will be no transcoding files produced"

**Comment by RTUnit** [comment]
That is expected behavior, because on startup Jellyfin is just testing FFMPEG on supported formats, and no playback/transcoding is yet occurring. So no purpose to monitor transcodes directory.

The cleanup will be started when client is starting media playback which will trigger ffmpeg.wrap. At that time there will be a filepath passed in argument by Jellyfin including transcoding directory, so then the cleanup process will keep running.

Are there any problems observed apart from this message in the log?

**Comment by ronajon** [comment]
thats the only behaviour that was making me questioning the workings of ffmeg
